version: "3.9"
services:
  classic-infra-db:
    image: postgres:16-alpine
    container_name: 'classic-infra-db'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    networks:
      - classic-infra

